# Generated by Django 5.1.6 on 2025-06-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
