# Generated by Django 5.1.6 on 2025-06-13 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0004_medicalrecord_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecord",
            name="summary",
        ),
    ]
