# Generated by Django 5.1.6 on 2025-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0005_remove_medicalrecord_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
