# Generated by Django 5.1.6 on 2025-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0006_medicalrecord_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
