# Generated by Django 5.2.3 on 2025-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0007_customuser_mobile_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecord",
            name="prescription",
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="prescription_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
